package com.balajitechlabs.quickdash.core.utils

import android.content.Context
import android.util.Log
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInAccount
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.Scope
import com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential
import com.google.api.client.http.FileContent
import com.google.api.client.http.javanet.NetHttpTransport
import com.google.api.client.json.gson.GsonFactory
import com.google.api.services.drive.Drive
import com.google.api.services.drive.DriveScopes
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.util.Collections

class GoogleDriveSyncManager(private val context: Context) {

    private val applicationName = "QuickDash"
    private val folderName = "appDataFolder"

    fun getSignInClient(): GoogleSignInClient {
        // Use default_web_client_id generated by google-services plugin if available
        val webClientId = try {
            context.getString(context.resources.getIdentifier("default_web_client_id", "string", context.packageName))
        } catch (e: Exception) {
            "" // Fallback if missing
        }

        val gsoBuilder = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestEmail()
            .requestProfile()
            .requestScopes(Scope(DriveScopes.DRIVE_FILE))
        
        if (webClientId.isNotEmpty()) {
            gsoBuilder.requestIdToken(webClientId)
        }

        return GoogleSignIn.getClient(context, gsoBuilder.build())
    }

    private fun getDriveService(account: GoogleSignInAccount): Drive {
        val credential = GoogleAccountCredential.usingOAuth2(
            context,
            Collections.singleton(DriveScopes.DRIVE_FILE)
        )
        credential.selectedAccount = account.account

        return Drive.Builder(
            NetHttpTransport(),
            GsonFactory.getDefaultInstance(),
            credential
        ).setApplicationName(applicationName).build()
    }

    suspend fun backupData(account: GoogleSignInAccount): Result<String> = withContext(Dispatchers.IO) {
        try {
            val driveService = getDriveService(account)
            val folderId = getOrCreateBackupFolder(driveService)
            
            val jsonString = BackupRestoreManager.getBackupJsonString(context)
            val tempFile = File(context.cacheDir, "quickdash_backup.json")
            tempFile.writeText(jsonString)
            
            uploadFileToDrive(driveService, tempFile, folderId)
            tempFile.delete()
            
            val folder = driveService.files().get(folderId).setFields("webViewLink").execute()
            Result.success(folder.webViewLink ?: "")
        } catch (e: Exception) {
            Log.e("DriveSync", "Backup failed", e)
            Result.failure(e)
        }
    }

    suspend fun restoreData(account: GoogleSignInAccount): Result<Unit> = withContext(Dispatchers.IO) {
        try {
            val driveService = getDriveService(account)
            val folderId = getOrCreateBackupFolder(driveService)
            
            val tempFile = File(context.cacheDir, "quickdash_backup.json")
            downloadFileFromDrive(driveService, "quickdash_backup.json", tempFile, folderId)
            
            if (tempFile.exists()) {
                val jsonString = tempFile.readText()
                val restoreResult = BackupRestoreManager.restoreFromJsonString(context, jsonString)
                tempFile.delete()
                
                if (restoreResult.isSuccess) {
                    Result.success(Unit)
                } else {
                    Result.failure(restoreResult.exceptionOrNull() ?: Exception("Restore failed"))
                }
            } else {
                Result.failure(Exception("Backup file not found in Google Drive folder"))
            }
        } catch (e: Exception) {
            Log.e("DriveSync", "Restore failed", e)
            Result.failure(e)
        }
    }

    private fun getOrCreateBackupFolder(driveService: Drive): String {
        val result = driveService.files().list()
            .setQ("mimeType='application/vnd.google-apps.folder' and name='QuickDash Backups' and trashed=false")
            .setSpaces("drive")
            .setFields("files(id, name)")
            .execute()
            
        if (result.files.isNotEmpty()) {
            return result.files[0].id
        }
        
        val folderMetadata = com.google.api.services.drive.model.File().apply {
            name = "QuickDash Backups"
            mimeType = "application/vnd.google-apps.folder"
        }
        val folder = driveService.files().create(folderMetadata)
            .setFields("id")
            .execute()
        return folder.id
    }

    private fun uploadFileToDrive(driveService: Drive, localFile: File, folderId: String) {
        val result = driveService.files().list()
            .setSpaces("drive")
            .setQ("name='${localFile.name}' and '$folderId' in parents and trashed=false")
            .setFields("files(id, name)")
            .execute()
        
        val fileContent = FileContent("application/octet-stream", localFile)
        
        if (result.files.isNotEmpty()) {
            val existingFileId = result.files[0].id
            val driveFile = com.google.api.services.drive.model.File()
            driveService.files().update(existingFileId, driveFile, fileContent).execute()
        } else {
            val driveFile = com.google.api.services.drive.model.File()
            driveFile.name = localFile.name
            driveFile.parents = listOf(folderId)
            driveService.files().create(driveFile, fileContent).execute()
        }
    }

    private fun downloadFileFromDrive(driveService: Drive, fileName: String, destFile: File, folderId: String) {
        val result = driveService.files().list()
            .setSpaces("drive")
            .setQ("name='$fileName' and '$folderId' in parents and trashed=false")
            .setFields("files(id, name)")
            .execute()
        
        if (result.files.isNotEmpty()) {
            val fileId = result.files[0].id
            destFile.parentFile?.mkdirs()
            FileOutputStream(destFile).use { out ->
                driveService.files().get(fileId).executeMediaAndDownloadTo(out)
            }
        }
    }
}