name = "quickdash-api"
main = "src/index.js"
compatibility_date = "2025-04-01"
workers_dev = false

routes = ["quickdash.balajitechlab.com/api/v1/feedback", "quickdash.balajitechlab.com/api/v1/crash-report"]

[[kv_namespaces]]
binding = "QUICKDASH_KV"
id = "880939f5c2e04092a891c18ab4475314"
